In [1]:
import sys, os
sys.path.insert(0, os.path.abspath("../.."))
print(sys.path)
%load_ext elastic.core.notebook.elastic_notebook

['/Users/libilly/elastic_notebook2/elastic-notebook', '/Users/libilly/elastic_notebook2/elastic-notebook/elastic/examples', '/Users/libilly/elastic_notebook2/elastic-notebook', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8', '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload', '', '/Users/libilly/elastic_notebook2/elastic-notebook/venv/lib/python3.8/site-packages']


In [2]:
%LoadCheckpoint checkpoints/numpy.pickle


Declaring variable np
Declaring variable datasets
Declaring variable KNeighborsClassifier
Rerunning cell 1
Rerunning cell 3
Declaring variable indices
Declaring variable knn
Rerunning cell 5
124
Declaring variable z


In [3]:
print(iris_X_test)
print(z)

[[5.4 3.9 1.7 0.4]
 [4.8 3.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [6.3 2.5 5.  1.9]
 [5.1 3.4 1.5 0.2]
 [5.4 3.  4.5 1.5]
 [5.4 3.4 1.5 0.4]
 [4.9 2.5 4.5 1.7]
 [5.5 3.5 1.3 0.2]
 [5.  3.4 1.5 0.2]]
2
